# Generated by Django 5.0 on 2024-01-06 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('realised_date', models.DateTimeField(blank=True, null=True)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='music.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=128, unique=True)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.album')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='music.artist')),
            ],
        ),
    ]
