# Generated by Django 5.0 on 2024-01-12 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='artist_id',
        ),
        migrations.CreateModel(
            name='Music_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_detail', models.TextField()),
                ('music_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.music')),
            ],
        ),
    ]
